---
title: "binned_experiments"
author: "Liyan Wang"
date: "2024-09-29"
output: html_document
---
```{r}
rm(list = ls())
library(survival)
library(dplyr)
library(caret)
library(ggplot2)
library(knitr)

knitr::purl("~/IPCweighting/SimulationFunction/IPCWmethod.Rmd", output = "~/IPCweighting/SimulationFunction/IPCWmethod.R")
source("~/IPCweighting/SimulationFunction/IPCWmethod.R")

knitr::purl("~/IPCweighting/IPCW/Binned_IPCW_Function.Rmd", output = "~/IPCweighting/IPCW/Binned_IPCW_Function.R")
source("~/IPCweighting/IPCW/Binned_IPCW_Function.R")

knitr::purl("~/IPCweighting/SimulationFunction/Status_table.Rmd", output = "~/IPCweighting/SimulationFunction/Status_table.R")
source("~/IPCweighting/SimulationFunction/Status_table.R")

knitr::purl("~/IPCweighting/SimulationFunction/Data_Simulation.Rmd", output = "~/IPCweighting/SimulationFunction/Data_Simulation.R")
source("~/IPCweighting/SimulationFunction/Data_Simulation.R")
```

```{r}
# Simulate covariates and event_time
num_obs = 600
time_point = 5
X = matrix(ncol = 0, nrow = 0)
mean_X = c()
X = get_cont_X(X, 'uniform',num_obs,1,4,"X1")
X = get_cont_X(X, 'uniform',num_obs,0.2,1,"X2")
X = get_cont_X(X, 'uniform',num_obs, 9, 20,"X3")
beta = sim_beta(0.6, time_point, mean_X) #sim_beta("uniform", length(mean_X),list(start = -2, end = 2))
if (ncol(X)!=length(beta)){
  stop("X and beta are not multiplicable")
}
var_name = colnames(X)
```

```{r}
dist = "log-logistic"
params = list()
time_point = 5
if(dist=="exponential"){
  params$lambda_base = 2
}else if(dist == "Weibull"){
  params$lambda_base = runif(1, 2, 4)
  params$alpha = runif(1, 0.1, 1)
} else if(dist == "log-logistic"){
  params$lambda_base = 1/3
  params$alpha = 2
} else if (dist == "log-normal"){
  params$mean = 1
  params$sd = 0.5
} else{
  stop("Unsupported distribution")
}

censor_dist = "uniform"
# censor_dist = dist
censor_params = list()
if(censor_dist=="exponential"){
  censor_params$lambda_base = params$lambda_base*0.2
}else if(censor_dist == "Weibull"){
  censor_params$lambda_base = params$lambda_base/2
  censor_params$alpha = params$alpha/2
} else if(censor_dist == "log-logistic"){
  censor_params$lambda_base = params$lambda_base/2
  censor_params$alpha = params$alpha
} else if (censor_dist == "log-normal"){
  censor_params$mean = params$mean
  censor_params$sd = params$sd/2
} else if (censor_dist == "uniform"){
  censor_params$start = 1.5
  censor_params$end = 7
} else{
  stop("Unsupported distribution")
}
plot_pdf(dist, params, time_point)
# plot_pdf(censor_dist, censor_params, time_point)
```

```{r}
params$lc = rowSums(sweep(X,2,beta,"*"))
power = exp(params$lc)
dt = simulation_data(num_obs, dist, params, censor_dist, censor_params, time_point, X)
dt$power = power
time_status = check_time_vs_status(dt$observed_time, dt$sigma, time_point)
censor_observations_interval = check_censor_in_time_interval(dt$observed_time, dt$sigma, time_point)
total_observations_interval = check_total_observations_in_time_interval(dt$observed_time, dt$sigma, time_point)
n_col = ncol(X)
print(time_status)
print(censor_observations_interval)
print(total_observations_interval)
# write.table(time_status,
#             file = sprintf("~/IPCweighting/Data/%s_lambda_%f_alpha_%f_%s_%f_covariates_data_ratio_Overall.txt",
#                      dist, params$lambda_base,params$alpha, censor_dist, n_col),
#             row.names = FALSE,
#             col.names = TRUE,
#             sep = "\t", quote = FALSE)
# write.table(censor_observations_interval,
#             file = sprintf("~/IPCweighting/Data/%s_lambda_%f_alpha_%f_%s_%f_covariates_data_ratio_Censor.txt",
#                      dist, params$lambda_base,params$alpha, censor_dist, n_col),
#             row.names = FALSE,
#             col.names = TRUE,
#             sep = "\t", quote = FALSE)
# write.table(total_observations_interval,
#             file = sprintf("~/IPCweighting/Data/%s_lambda_%f_alpha_%f_%s_%f_covariates_data_ratio_Interval.txt",
#                      dist, params$lambda_base,params$alpha, censor_dist, n_col),
#             row.names = FALSE,
#             col.names = TRUE,
#             sep = "\t", quote = FALSE)

print(paste("The ratio of observations occured of the total observations which have observed time greater than 2.5 years",nrow(dt[dt$observed_time > time_point/2 & dt$observed_time  < time_point & dt$sigma == 1, ])/nrow(dt[dt$observed_time > time_point/2 & dt$observed_time < time_point, ])))
```

```{r}
# Cross Validation, binning intervals equally
max_intervals = 40
k = 5
results = data.frame(intervals = 1:max_intervals, performance_combined_LH = NA, performance_combined_C = NA, performance_separate_LH = NA, performance_separate_C = NA, performance_separate_ols = NA)
for (num_intervals in 1:max_intervals) {
  fold_performance_separate_LH = numeric(k)
  fold_performance_separate_C = numeric(k)
  fold_performance_separate_ols = numeric(k)
  
  fold_performance_combined_LH = numeric(k)
  fold_performance_combined_C = numeric(k)
  fold_performance_combined_ols = numeric(k)
  folds = createFolds(dt$event_time, k = k)
  for (f in 1:k) {
    train_data = dt[-folds[[f]], ]
    test_data = dt[folds[[f]], ]
    # Ghat = Get_Ghat(time_point, train_data)
    test_IPCW = get_IPCW_relevant(test_data, time_point, return_type = "IPCW")
    interval = seq(0, time_point, length.out = num_intervals + 1)
    
    # SEPARATED VERSION
    model_list = bin_separate_ipcw(interval, train_data)
    pred_survival_probability = bin_surv_probability(model_list, test_data, var_name)
    pred_separate_surv_prob = apply(pred_survival_probability, 1, prod)
    fold_performance_separate_LH[f] = weighted_loglikelihood(test_IPCW, test_data$E, 1-pred_separate_surv_prob)
    fold_performance_separate_C[f] = c_index_censoring(test_data$observed_time, test_data$sigma, 1-pred_separate_surv_prob)
    test_true_surv = (true_survival_function(dist, time_point,
                                            params = params)) ^exp(rowSums(sweep(test_data[var_name],2,beta,"*")))
    fold_performance_separate_ols[f] = ols_error(test_true_surv, pred_separate_surv_prob)
    
    results$performance_separate_LH[num_intervals] = mean(fold_performance_separate_LH)
    results$performance_separate_C[num_intervals] = mean(fold_performance_separate_C)
    results$performance_separate_ols[num_intervals] = mean(fold_performance_separate_ols)
    
    #COMBINED
    model = bin_combined_ipcw(interval, train_data)
    pred_combine_event_prob = predict(model, newdata = test_data[var_name], type = "response")
    pred_combine_surv_prob = 1 - pred_combine_event_prob
    fold_performance_combined_LH[f] = weighted_loglikelihood(test_IPCW, test_data$E, 1-(pred_combine_surv_prob)^num_intervals)
    fold_performance_combined_C[f] = c_index_censoring(test_data$observed_time, test_data$sigma, 1-(pred_combine_surv_prob)^num_intervals)
    fold_performance_combined_ols[f] = ols_error(test_true_surv, pred_combine_surv_prob^num_intervals)
  }
  results$performance_combined_LH[num_intervals] = mean(fold_performance_combined_LH)
  results$performance_combined_C[num_intervals] = mean(fold_performance_combined_C)
  results$performance_combined_ols[num_intervals] = mean(fold_performance_combined_ols)
}
best_intervals_separate_LH = results$intervals[which.min(results$performance_separate_LH)]
best_intervals_separate_C = results$intervals[which.max(results$performance_separate_C)]
best_intervals_separate_ols = results$intervals[which.min(results$performance_separate_ols)]

best_intervals_combined_LH = results$intervals[which.min(results$performance_combined_LH)]
best_intervals_combined_C = results$intervals[which.max(results$performance_combined_C)]
best_intervals_combined_ols = results$intervals[which.min(results$performance_combined_ols)]

print(dist)
print(params$lambda_base)
print(params$alpha)
plot_pdf(dist, params, time_point)
print(check_time_vs_status(dt$observed_time, dt$sigma, time_point))
print(check_censor_in_time_interval(dt$observed_time, dt$sigma, time_point))
print(check_total_observations_in_time_interval(dt$observed_time, dt$sigma, time_point))
# plot_pdf("exponential", list(lambda_base = 2), time_point)


method = c("LogLikelihood (Combined)", "C-index (Combined)", "OLS (Combined)", 
            "LogLikelihood (Separate)", "C-index (Separate)", "OLS (Separate)")
optimal_intervals = c(best_intervals_combined_LH, best_intervals_combined_C, best_intervals_combined_ols,
                       best_intervals_separate_LH, best_intervals_separate_C, best_intervals_separate_ols)
results_df = data.frame(Method = method, Optimal_Intervals = optimal_intervals)
results_df
# write.table(results_df,
#             file = sprintf("~/IPCweighting/Data/%s_lambda_%f_alpha_%f_%s_%f_covariates_results.txt",
#                      dist, params$lambda_base,params$alpha, censor_dist, n_col),
#             row.names = FALSE,
#             col.names = TRUE,
#             sep = "\t", quote = FALSE)


```

```{r}
# Plot of performance with respect to the number of bins
# fileName = sprintf("~/IPCweighting/Images/%s_%s_%d_LL_CombinedBins.png", dist, censor_dist, n_col) 
plot(x=c(1:max_intervals),
     y = results$performance_combined_LH,
     xlab = "Number of Intervals",
     ylab = "-log_likelihood",
     main = "-Log-Likelihood vs. Number of Bins with Combined Binned IPCW")
abline(v = best_intervals_combined_LH, col = "red", lty = 2, lwd = 2)
plot(x=c(1:max_intervals), y = results$performance_combined_C, xlab = "Number of Intervals")
plot(x=c(1:max_intervals), y = results$performance_combined_ols, xlab = "Number of Intervals")

# FileName = sprintf("~/IPCweighting/Images/%s_%s_%d_LL_SeparatedBins.png")
plot(x = c(1:max_intervals), y = results$performance_separate_LH,
     xlab = "Number of Intervals",
     ylab = "-log_likelihood",
     main = "-Log-Likelihood vs. Number of Bins with Separated Binned IPCW")
abline(v = best_intervals_separate_LH, col = "red", lty = 2, lwd = 2)
plot(x=c(1:max_intervals), y = results$performance_separate_C, xlab = "Number of Intervals")
plot(x=c(1:max_intervals), y = results$performance_separate_ols, xlab = "Number of Intervals")
```


```{r}
png(file = sprintf("~/IPCweighting/Images/%s_lambda_%f_alpha_%f_%s_%f__LL_CombinedBins.png", dist, params$lambda_base, params$alpha, censor_dist, n_col), 
    width = 800, height = 600)
# Plot 1: -Log-Likelihood (Combined)
plot(x = c(1:max_intervals), 
     y = results$performance_combined_LH, 
     xlab = "Number of Intervals", 
     ylab = "-log_likelihood", 
     main = "-Log-Likelihood vs. Number of Bins with Combined Binned IPCW")
abline(v = best_intervals_combined_LH, col = "red", lty = 2, lwd = 2)
dev.off()

# Save the second plot to a file
png(file = sprintf("~/IPCweighting/Images/%s_lambda_%f_alpha_%f_%s_%f_C_CombinedBins.png", dist, params$lambda_base, params$alpha, censor_dist, n_col), 
    width = 800, height = 600)
plot(x = c(1:max_intervals), 
     y = results$performance_combined_C, 
     xlab = "Number of Intervals", 
     ylab = "C-index", 
     main = "C-index vs. Number of Bins with Combined Binned IPCW")
abline(v = best_intervals_combined_C, col = "red", lty = 2, lwd = 2)
dev.off()

# Save the third plot
png(file = sprintf("~/IPCweighting/Images/%s_lambda_%f_alpha_%f_%s_%f_OLS_CombinedBins.png", dist, params$lambda_base, params$alpha, censor_dist, n_col), 
    width = 800, height = 600)
plot(x = c(1:max_intervals), 
     y = results$performance_combined_ols, 
     xlab = "Number of Intervals", 
     ylab = "OLS Error", 
     main = "OLS Error vs. Number of Bins with Combined Binned IPCW")
abline(v = best_intervals_combined_ols, col = "red", lty = 2, lwd = 2)
dev.off()


# Save the plot for Separated Bins -Log-Likelihood
png(file = sprintf("~/IPCweighting/Images/%s_lambda_%f_alpha_%f_%s_%f_LL_SeparatedBins.png", dist, params$lambda_base, params$alpha, censor_dist, n_col), 
    width = 800, height = 600)
plot(x = c(1:max_intervals), 
     y = results$performance_separate_LH, 
     xlab = "Number of Intervals", 
     ylab = "-log_likelihood", 
     main = "-Log-Likelihood vs. Number of Bins with Separated Binned IPCW")
abline(v = best_intervals_separate_LH, col = "red", lty = 2, lwd = 2)
dev.off()

png(file = sprintf("~/IPCweighting/Images/%s_lambda_%f_alpha_%f_%s_%f_C_SeparatedBins.png", dist, params$lambda_base, params$alpha, censor_dist, n_col), 
    width = 800, height = 600)
plot(x = c(1:max_intervals), 
     y = results$performance_separate_C, 
     xlab = "Number of Intervals", 
     ylab = "C-index", 
     main = "C-index vs. Number of Bins with Separated Binned IPCW")
abline(v = best_intervals_separate_C, col = "red", lty = 2, lwd = 2)
dev.off()


png(file = sprintf("~/IPCweighting/Images/%s_lambda_%f_alpha_%f_%s_%f_OLS_SeparatedBins.png", dist, params$lambda_base, params$alpha, censor_dist, n_col), 
    width = 800, height = 600)
plot(x = c(1:max_intervals), 
     y = results$performance_separate_ols, 
     xlab = "Number of Intervals", 
     ylab = "ols", 
     main = "ols vs. Number of Bins with Separated Binned IPCW")
abline(v = best_intervals_separate_ols, col = "red", lty = 2, lwd = 2)
dev.off()

```

```{r}
# Compute 1 bin IPCW ols_error
true_surv = (true_survival_function(dist, time_point, params = params))^power
ipcw_est_surv = ipcw_estimate(dt,dt, time_point, var_name)
ols_ipcw = ols_error(true_surv,ipcw_est_surv)
ols_ipcw

# Compute optimal_bin IPCW ols_error
opt_interval = seq(0, time_point, length.out = best_intervals_combined + 1)
multi_ipcw_model = bin_combined_ipcw(opt_interval, dt)
multi_layer_ipcw_pred_prob = 1-(predict(multi_ipcw_model, newdata = dt[var_name], type = "response"))
ols_bin_combine_ipcw = ols_error(true_surv, (multi_layer_ipcw_pred_prob)^best_intervals_combined)
ols_bin_combine_ipcw

# Optimal_bin separate IPCW ols_error
opt_interval_separate = seq(0, time_point, length.out = best_intervals_separate + 1)
model_list = bin_separate_ipcw(opt_interval_separate, dt)
pred_survival_probability = bin_surv_probability(model_list, dt, var_name)
pred_separate_prob = apply(pred_survival_probability, 1, prod)
ols_bin_separate_ipcw = ols_error(true_surv, pred_separate_prob)
ols_bin_separate_ipcw
```

