---
title: "Binned_ClassificationTree_Experiments"
author: "Liyan Wang"
date: "2024-10-12"
output: pdf_document
---

```{r}
rm(list = ls())
library(rpart)
library(survival)
library(dplyr)
library(caret)
library(ggplot2)
library(knitr)

knitr::purl("~/IPCweighting/IPCW/Binned_IPCW_ClassificationTree.Rmd", output = "~/IPCweighting/IPCW/Binned_IPCW_ClassificationTree.R")
source("~/IPCweighting/IPCW/Binned_IPCW_ClassificationTree.R")

knitr::purl("~/IPCweighting/SimulationFunction/Data_Simulation.Rmd", output = "~/IPCweighting/SimulationFunction/Data_Simulation.R")
source("~/IPCweighting/SimulationFunction/Data_Simulation.R")

knitr::purl("~/IPCweighting/SimulationFunction/Status_table.Rmd", output = "~/IPCweighting/SimulationFunction/Status_table.R")
source("~/IPCweighting/SimulationFunction/Status_table.R")
```

```{r}
dist = "exponential"
params = list()
time_point = 5
if(dist=="exponential"){
  params$lambda_base = 2
}else if(dist == "Weibull"){
  params$lambda_base = 1/3
  params$alpha = runif(1, 1.1, 4)
} else if(dist == "log-logistic"){
  params$lambda_base = runif(1, 2, 4)
  params$alpha = runif(1, 0.1, 1)
} else if (dist == "log-normal"){
  params$mean = 1
  params$sd = 0.5
} else{
  stop("Unsupported distribution")
}

censor_dist = "uniform"
# censor_dist = dist
censor_params = list()
if(censor_dist=="exponential"){
  censor_params$lambda_base = params$lambda_base*0.2
}else if(censor_dist == "Weibull"){
  censor_params$lambda_base = params$lambda_base*0.1
  censor_params$alpha = params$alpha/2
} else if(censor_dist == "log-logistic"){
  censor_params$lambda_base = params$lambda_base/2
  censor_params$alpha = params$alpha
} else if (censor_dist == "log-normal"){
  censor_params$mean = params$mean
  censor_params$sd = params$sd/2
} else if (censor_dist == "uniform"){
  censor_params$start = 2
  censor_params$end = time_point+3
} else{
  stop("Unsupported distribution")
}
params
plot_pdf(dist,params,time_point)
```

```{r}
num_obs = 500
time_point = 5
num_covariates = 10
X = matrix(rnorm(num_obs*num_covariates), nrow=num_obs, ncol = num_covariates)
colnames(X) = paste0("X", 1:num_covariates)
var_name = colnames(X)
num_beta = 4
beta = c(rnorm(num_beta, mean = 0.9, sd = 0.7), rep(0,  num_covariates-num_beta)) 
Y_continuous = generate_Y_continuous(X, c(1:num_covariates), beta)
data_tree = as.data.frame(X)
data_tree$Y_continuous = Y_continuous
tree_model_fX = rpart(Y_continuous ~ ., data = data_tree)
f_X = predict(tree_model_fX, data_tree)
params$lc = f_X
power = exp(params$lc)

dt = simulation_data(num_obs, dist, params, censor_dist, censor_params, time_point, X)
dt$power = power
print(check_time_vs_status(dt$observed_time, dt$sigma, time_point))
print(check_censor_in_time_interval(dt$observed_time, dt$sigma, time_point))
print(check_total_observations_in_time_interval(dt$observed_time, dt$sigma, time_point))
```

```{r}
loss_ratios =seq(2.5, 10, by = 1)
min_samples_leaf_values = c(10,20,30,50)#,70,90)
ccp_alpha_values = 10^seq(-1, -4, length =20)
fit_classification_tree(dt, var_name, loss_ratios, min_samples_leaf_values, ccp_alpha_values, time_point, max_intervals = 2, k = 5, proxy_data = NULL)

```

