---
title: "lasso_experiments"
author: "Liyan Wang"
date: "2024-10-02"
output: html_document
---

```{r}
rm(list = ls())
library(survival)
library(dplyr)
library(caret)
library(ggplot2)
library(knitr)
knitr::purl("~/IPCweighting/IPCW/Lasso_single_binned.Rmd", output = "~/IPCweighting/IPCW/Lasso_single_binned.R")
source("~/IPCweighting/IPCW/Lasso_single_binned.R")

knitr::purl("~/IPCweighting/SimulationFunction/Data_Simulation.Rmd", output = "~/IPCweighting/SimulationFunction/Data_Simulation.R")
source("~/IPCweighting/SimulationFunction/Data_Simulation.R")


knitr::purl("~/IPCweighting/SimulationFunction/Status_table.Rmd", output = "~/IPCweighting/SimulationFunction/Status_table.R")
source("~/IPCweighting/SimulationFunction/Status_table.R")
```

```{r}
# Simulate covariates and event_time
num_obs = 500
time_point = 5
num_covariates = 300
X = matrix(rnorm(num_obs*num_covariates), nrow=num_obs, ncol = num_covariates)
colnames(X) = paste0("X", 1:num_covariates)
mean_X = c()
num_beta = 200
beta = c(rnorm(num_beta, mean = 0.5, sd = 0.7), rep(0.01,  num_covariates-num_beta)) 
# length(mean_X),list(start = -2, end = 2))
if (ncol(X)!=length(beta)){
  stop("X and beta are not multiplicable")
}
var_name = colnames(X)
```

```{r}
dist = "log-logistic"
params = list()
time_point = 5
if(dist=="exponential"){
  params$lambda_base = 2
}else if(dist == "Weibull"){
  params$lambda_base = runif(1, 2, 4)
  params$alpha = runif(1, 0.1, 1)
} else if(dist == "log-logistic"){
  params$lambda_base = runif(1, 2, 4)
  params$alpha = runif(1, 0.1, 1)
} else if (dist == "log-normal"){
  params$mean = 1
  params$sd = 0.5
} else{
  stop("Unsupported distribution")
}

censor_dist = "uniform"
# censor_dist = dist
censor_params = list()
if(censor_dist=="exponential"){
  censor_params$lambda_base = params$lambda_base*0.2
}else if(censor_dist == "Weibull"){
  censor_params$lambda_base = params$lambda_base*0.1
  censor_params$alpha = params$alpha/2
} else if(censor_dist == "log-logistic"){
  censor_params$lambda_base = params$lambda_base/2
  censor_params$alpha = params$alpha
} else if (censor_dist == "log-normal"){
  censor_params$mean = params$mean
  censor_params$sd = params$sd/2
} else if (censor_dist == "uniform"){
  censor_params$start = 1
  censor_params$end = 8
} else{
  stop("Unsupported distribution")
}
params
plot_pdf(dist,params,time_point)
```

```{r}
params$lc = rowSums(sweep(X,2,beta,"*"))
power = exp(params$lc)
dt = simulation_data(num_obs, dist, params, censor_dist, censor_params, time_point, X)
dt$power = power
print(check_time_vs_status(dt$observed_time, dt$sigma, time_point))
print(check_censor_in_time_interval(dt$observed_time, dt$sigma, time_point))
print(check_total_observations_in_time_interval(dt$observed_time, dt$sigma, time_point))
```

```{r}
lambda_values = 10^seq(-1, -3, length = 50)
# Lasso
alpha_num=1
max_interval = 30
results = cross_validate_lambda(dt, lambda_values, var_name, alpha=alpha_num, time_point, max_intervals = max_interval)
  
optimal_results = data.frame(
    Metric = c("OLS", "C-index", "Log-Likelihood"),
    Optimal_Lambda_Index = integer(3),
    Optimal_Number_of_Intervals = integer(3),
    Optimal_Value = numeric(3)
  )
  
  # 1. Find the optimal lambda and number of intervals for OLS (results[,, 1])
  min_val_ols = min(results[,, 1], na.rm = TRUE)
  optimal_index_ols = which(results[,, 1] == min_val_ols, arr.ind = TRUE)
  optimal_lambda_ols = lambda_values[optimal_index_ols[1, 1]]
  optimal_intervals_ols = optimal_index_ols[1, 2]
  
  # 2. Find the optimal lambda and number of intervals for C-index (results[,, 2])
  max_val_cindex = max(results[,, 2], na.rm = TRUE)
  optimal_index_cindex = which(results[,, 2] == max_val_cindex, arr.ind = TRUE)
  optimal_lambda_cindex = lambda_values[optimal_index_cindex[1, 1]]
  optimal_intervals_cindex = optimal_index_cindex[1, 2]
  
  # 3. Find the optimal lambda and number of intervals for Log-Likelihood (results[,, 3])
  min_val_ll = min(results[,, 3], na.rm = TRUE)
  optimal_index_ll = which(results[,, 3] == min_val_ll, arr.ind = TRUE)
  optimal_lambda_ll = lambda_values[optimal_index_ll[1, 1]]
  optimal_intervals_ll = optimal_index_ll[1, 2]
  
  # Store the results in the data frame
  optimal_results[1, ] = c("OLS", optimal_lambda_ols, optimal_intervals_ols, min_val_ols)
  optimal_results[2, ] = c("C-index", optimal_lambda_cindex, optimal_intervals_cindex, max_val_cindex)
  optimal_results[3, ] = c("-Log-Likelihood", optimal_lambda_ll, optimal_intervals_ll, min_val_ll)
  
  # Ensure the lambda indices are numeric, not character
  optimal_results$Optimal_Lambda_Index = as.numeric(optimal_results$Optimal_Lambda_Index)
  optimal_results$Optimal_Number_of_Intervals = as.numeric(optimal_results$Optimal_Number_of_Intervals)
  optimal_results$Optimal_Value = as.numeric(optimal_results$Optimal_Value)
  
print(optimal_results)

plot(c(1:max_interval),results[optimal_index_ols[1, 1],,1],
     xlab = "Number of Intervals",
     ylab = "OLS Error",
     main = paste("OLS Error vs. number of Intervals of optimal tuning parameter: ",round(optimal_lambda_ols,4)))
plot(c(1:max_interval),results[optimal_index_cindex[1, 1],,2],
     xlab = "Number of Intervals",
     ylab = "C-index",
     main = paste("C-index vs. number of Intervals of optimal tuning parameter: ",round(optimal_lambda_cindex,4)))
plot(c(1:max_interval),results[optimal_index_ll[1, 1],,3],
     xlab = "Number of Intervals",
     ylab = "-Log-Likelihood",
     main = paste("-Log-Likelihood vs. number of Intervals of optimal tuning parameter: ",round(optimal_lambda_ll,4)))

```

```{r}

```

