---
title: "IPCW_ClassificationTree"
author: "Liyan Wang"
date: "2024-10-11"
output: html_document
---

```{r}
rm(list = ls())
library(rpart)
library(survival)
library(dplyr)
library(caret)
library(ggplot2)
library(knitr)
install.packages("rpart.plot")
library(rpart.plot)

knitr::purl("~/IPCweighting/SimulationFunction/IPCWmethod.Rmd", output = "~/IPCweighting/SimulationFunction/IPCWmethod.R")
source("~/IPCweighting/SimulationFunction/IPCWmethod.R")

knitr::purl("~/IPCweighting/IPCW/Binned_IPCW_Function.Rmd", output = "~/IPCweighting/IPCW/Binned_IPCW_Function.R")
source("~/IPCweighting/IPCW/Binned_IPCW_Function.R")

knitr::purl("~/IPCweighting/SimulationFunction/Status_table.Rmd", output = "~/IPCweighting/SimulationFunction/Status_table.R")
source("~/IPCweighting/SimulationFunction/Status_table.R")

knitr::purl("~/IPCweighting/SimulationFunction/Data_Simulation.Rmd", output = "~/IPCweighting/SimulationFunction/Data_Simulation.R")
source("~/IPCweighting/SimulationFunction/Data_Simulation.R")
```

```{r}
generate_Y_continuous <- function(X, ind, beta) {
  if (length(ind) != length(beta)) {
    stop("Length of 'ind' and 'beta' must be the same.")
  }
  linear_part = X[, ind] %*% beta
  Y_continuous = linear_part + rnorm(nrow(X))
  return(Y_continuous)
}
```

```{r}
weighted_misclassification_rate <- function(true_labels, predicted_labels, ipcw_weights) {
  if (length(true_labels) != length(predicted_labels) || length(true_labels) != length(ipcw_weights)) {
    stop("The length of true labels, predicted labels, and IPCW weights must be the same.")
  }
  weighted_incorrect = sum(ifelse(ipcw_weights == 0,
                                   0,
                                   ipcw_weights * (true_labels != predicted_labels)))
  total_weight = sum(ipcw_weights)
  weighted_misclassification_rate = weighted_incorrect / total_weight
  return(weighted_misclassification_rate)
}
```

```{r}
predict_nodes <- function (object, newdata, na.action = na.pass) {
        where <-
            if (missing(newdata)) 
                object$where
            else {
                if (is.null(attr(newdata, "terms"))) {
                    Terms <- delete.response(object$terms)
                    newdata <- model.frame(Terms, newdata, na.action = na.action, 
                                           xlev = attr(object, "xlevels"))
                    if (!is.null(cl <- attr(Terms, "dataClasses"))) 
                        .checkMFClasses(cl, newdata, TRUE)
                }
                rpart:::pred.rpart(object, rpart:::rpart.matrix(newdata))
            }
        as.integer(row.names(object$frame))[where]
    }
```

```{r}
fit_classification_tree <- function(data, var_name, loss_ratios, min_samples_leaf_values, ccp_alpha_values, time_point, max_intervals = 40, k = 5, proxy_data = NULL) {
  result_matrix <- matrix(NA, nrow = max_intervals, ncol = 8)
  colnames(result_matrix) <- c("num_intervals", "min_samples_leaf", "ccp_alpha", "loss_ratio", "C_index", "Brier Score", "OLS Error", "-Log-Likelihood")
  folds = createFolds(dt$observed_time, k = k)
  for (num_intervals in 1:max_intervals) {
    interval = seq(0, time_point, length.out = num_intervals + 1)
    cv_results = expand.grid(
      min_samples_leaf = min_samples_leaf_values,
      ccp_alpha = ccp_alpha_values,
      loss_ratio = loss_ratios
    )
    cv_results$C_index = NA
    cv_results$brier_score = NA
    cv_results$ols_error = NA
    cv_results$ll = NA
    for (i in seq_len(nrow(cv_results))) {
      min_samples_leaf = cv_results$min_samples_leaf[i]
      ccp_alpha = cv_results$ccp_alpha[i]
      loss_ratio = cv_results$loss_ratio[i]
      loss_matrix = matrix(c(0, 1, loss_ratio, 0), ncol = 2)
      fold_performance_c_index = numeric(length(folds))
      fold_performance_brier_score = numeric(length(folds))
      fold_performance_ols = numeric(length(folds))
      fold_performance_ll = numeric(length(folds))
      for (j in seq_along(folds)) {
        train_data = data[-folds[[j]], ]
        test_data = data[folds[[j]], ]
        test_true_surv = (true_survival_function(dist, time_point, params = params))^(test_data$power)
        if(!is.null(proxy_data)){
          # Get the IPCW values for the combined data
          test_data_modified = test_data %>% select(-power)
          test_proxy = rbind(test_data_modified, proxy_data)
          total_IPCW = get_IPCW_relevant(test_proxy, time_point, return_type = "IPCW")
          # Extract the IPCW values corresponding to test_data
          test_IPCW = total_IPCW[1: nrow(test_data)]
        }
        else{
          test_IPCW = get_IPCW_relevant(test_data, time_point, return_type = "IPCW")
        }
        # Get the expanded train dataset using combined IPCW
        expanded_train_data_with_weight = bin_combined_ipcw(interval,train_data, return_type="dataset")
        # train_weight_X = expanded_train_data_with_weight[var_name,]
        valid_indices = which(expanded_train_data_with_weight$IPCW > 0)
        # filtered_train_X = train_weight_X[valid_indices, ]
        filtered_train_E = expanded_train_data_with_weight$E[valid_indices]
        filtered_weights = expanded_train_data_with_weight$IPCW[valid_indices]
        formula = as.formula(paste("E ~", paste(var_name, collapse = " + ")))
        # Fit the classification tree with BINNED IPCW weights
        model_data = expanded_train_data_with_weight[valid_indices,]
        tree_model = rpart(formula,
                            data = model_data,
                            weights = filtered_weights,
                            method = "class",
                            parms = list(loss = loss_matrix),
                            control = rpart.control(minbucket = min_samples_leaf, cp = ccp_alpha))
        # rpart.plot(tree_model, type = 2, extra = 104, fallen.leaves = TRUE)
        train_node_indices = predict_nodes(tree_model, model_data)
        test_node_indices = predict_nodes(tree_model, test_data)
        # est_test_label = predict(tree_model, newdata = test_data, type = "class")
        node_probabilities = tapply(X = filtered_weights * filtered_train_E,
                                    INDEX = train_node_indices,
                                    FUN = sum) / tapply(filtered_weights, INDEX=train_node_indices, FUN = sum)
        node_probabilities = setNames(node_probabilities, names(node_probabilities))
        est_test_event_single = node_probabilities[as.character(test_node_indices)]
        est_test_surv_probability = (1-est_test_event_single)^num_intervals
        est_test_event_probability = 1-est_test_surv_probability
        # est_test_event_probability = predict(tree_model, newdata = test_data, type = "prob")[, 2]
        fold_performance_c_index[j] = c_index_censoring(test_data$observed_time,
                                                        test_data$sigma,
                                                        est_test_event_probability)
        fold_performance_ols[j] = ols_error(test_true_surv, 1-est_test_event_probability)
        fold_performance_brier_score[j] = Weighted_Brier_Score(est_test_event_probability,
                                                               test_data$E, 
                                                               test_IPCW)
        fold_performance_ll[j] = weighted_loglikelihood(test_IPCW, 
                                                        test_data$E, 
                                                        est_test_event_probability)
      }
      cv_results$C_index[i] = mean(fold_performance_c_index)
      cv_results$brier_score[i] = mean(fold_performance_brier_score)
      cv_results$ols_error[i] = mean(fold_performance_ols)
      cv_results$ll[i] = mean(fold_performance_ll)
    }
    # Find the best model based on the highest C-index
    best_c_index = max(cv_results$C_index)
    se_best = sd(cv_results$C_index)
    print(se_best)
    best_models = cv_results %>% filter(C_index >= best_c_index - se_best)
    selected_model = best_models %>%
      mutate(score = (min_samples_leaf / max(min_samples_leaf)) + (ccp_alpha / max(ccp_alpha)) - (loss_ratio / max(loss_ratio))) %>%
      arrange(desc(score)) %>%
      slice(1)
  
    result_matrix[num_intervals, ] = c(num_intervals, selected_model$min_samples_leaf,
                                       selected_model$ccp_alpha, selected_model$loss_ratio,
                                       selected_model$C_index,selected_model$brier_score,
                                       selected_model$ols_error, selected_model$ll)
  }
  return(result_matrix)
}
```
