---
title: "naive_cox_ipcw"
author: "Liyan Wang"
date: "2024-09-27"
output: html_document
---

```{r}
naive_estimate <- function(dt, newdt, var_name){
  # Estimates survival probability at a given time point using a naive logistic regression approach.
  # Arguments:
  #   newdt: the dataset that you want to estimate survival probability
  #   var_name: A vector containing the names of all covariates to be included in the model.
  # Returns:
  #   A vector of predicted survival probabilities for each observation at the specified time point.
  naive_data = dt[!is.na(dt$E),]  # drop observations with unknown E
  formula = as.formula(paste("E ~", paste(var_name, collapse = " + ")))
  naive_model = glm(formula, data = naive_data, family = binomial)
  predicted_prob = predict(naive_model, newdata = newdt[var_name], type = "response")
  predicted_prob = pmax(pmin(predicted_prob, 1 - 1e-15), 1e-15)
  naive_newdt_survival_prob = 1-(predicted_prob)
  return(naive_newdt_survival_prob)
}
```

```{r}
cox_estimate<-function(dt,newdt, var_name){
  # Estimates survival probability at a given time point using a cox ph model
  # Arguments:
  #   time_point: Numeric value specifying the time point of interest.
  #   var_name: A vector containing the names of all covariates to be included in the model.
  # Returns:
  #   A vector of predicted survival probabilities for each observation at the specified time point.
  formula = as.formula(paste("Surv(observed_time, sigma) ~", paste(var_name, collapse = " + ")))
  cox_model = coxph(formula, data = dt)
  coxph_pred_prob = predict(cox_model, newdata = newdt, type="survival")
  coxph_newdt_survival_prob = pmax(pmin(coxph_pred_prob, 1 - 1e-15), 1e-15)
  return(coxph_newdt_survival_prob)
}
```

```{r}
get_IPCW_relevant <- function(dt, time_point, return_type = "data"){
  km_censor_Xi = survfit(Surv(observed_time, 1-sigma)~1, data = dt)
  survest_Xi = stepfun(km_censor_Xi$time, c(1, km_censor_Xi$surv))
  censor_prob_Xi = survest_Xi(ifelse(dt$observed_time<time_point, dt$observed_time,time_point))
  dt$G_hat_Vi = censor_prob_Xi
  IPCW = ifelse(pmin(dt$event_time, time_point)<dt$censor_time, 1/pmax(dt$G_hat_Vi, 1e-15), 0)
  if (return_type == "IPCW"){
    return(IPCW)
  }
  else{
    dt$IPCW = IPCW
    return(dt)
  }
}
```

```{r}
ipcw_estimate <- function(dt,newdt, time_point, var_name){
  # Estimates survival probability at a given time point using a naive logistic regression approach with IPCW.
  # Arguments:
  #   newdt: the dataset that you want to estimate survival probability
  #   time_point: Numeric value specifying the time point of interest.
  #   var_name: A vector containing the names of all covariates to be included in the model.
  # Returns:
  #   A vector of predicted survival probabilities for each observation at the specified time point with IPCW.
  #Apply Kaplan-Meier estimator of the survival distribution of the censoring times
  full_dt = get_IPCW_relevant(dt, time_point)
  formula = as.formula(paste("E ~", paste(var_name, collapse = " + ")))
  ipcw_logistic_model = glm(formula, data = full_dt, family = binomial, weights = IPCW)
  ipcw_pred_prob = 1-predict(ipcw_logistic_model, newdata = newdt[var_name], type = "response")
  ipcw_survival_prob <- pmax(pmin(ipcw_pred_prob, 1 - 1e-15), 1e-15)
  return(ipcw_survival_prob)
}
```

