---
title: "LASSO_single_binned"
author: "Liyan Wang"
date: "2024-10-01"
output: html_document
---
```{r}
rm(list = ls())
library(survival)
library(dplyr)
library(caret)
library(ggplot2)
library(knitr)
library(glmnet)
knitr::purl("~/IPCweighting/IPCW/Binned_IPCW_Function.Rmd", output = "~/IPCweighting/IPCW/Binned_IPCW_Function.R")
source("~/IPCweighting/IPCW/Binned_IPCW_Function.R")
```

```{r}
# Cross-validation function for LASSO OR Ridge OR Elastic Net in Logistic OR Cox model
cross_validate_lambda <- function(dt, lambda_values, var_name, alpha_num, time_point, max_intervals = 60, k = 5, method = "glm") {
  # This function performs k-fold cross-validation for a penalized logistic regression
  # or Cox proportional hazards model using different regularization parameters (lambda values and the number of intervals).
  # Arguments:
  # dt: Dataframe containing the dataset with covariates and event status.
  # lambda_values: A grid of regularization parameters (lambda) to test.
  # var_name: A vector of variable names to use as predictors in the model.
  # alpha_num: Alpha parameter for glmnet, controls the type of regularization (0 = ridge, 1 = lasso, 0 < alpha < 1 = elastic net).
  # time_point: A predefined time point at which to evaluate the survival probabilities.
  # max_intervals: Maximum number of intervals for binning IPCW weights (default = 60).
  # k: Number of folds for cross-validation (default = 5).
  # method: The type of model to fit.
  #         Options are "glm" for logistic regression and "cox" for Cox proportional hazards.
  n = nrow(dt)
  X = dt[var_name]
  folds = sample(rep(1:k, length.out = n))
  results <- array(0, dim = c(length(lambda_values), max_intervals, 3))
  for (num_intervals in 1:max_intervals) {
    # fold performance_metric[i, 1, j] represents OLS Error with lambda_value[i] and j intervals
    # fold performance_metric[i, 2, j] represents C-index with lambda_value[i] and j intervals
    # fold performance_metric[i, 3, j] represents -Log-likelihood with lambda_value[i] and j intervals
    fold_performance_metric = array(0, dim = c(length(lambda_values), 3, k))
    for (f in 1:k) {
      train_data = dt[folds!=f,]
      test_data = dt[folds==f,]
      test_IPCW = get_IPCW_relevant(test_data, time_point, return_type = "IPCW")
      test_true_surv = (true_survival_function(dist, time_point, params = params))^(test_data$power)
      # Get the expanded train dataset using combined IPCW
      expanded_train_data_with_weight = bin_combined_ipcw(interval,train_data, return_type="dataset")
      train_weight_X = expanded_train_data_with_weight[var_name]
      valid_indices <- which(expanded_train_data_with_weight$IPCW > 0)
      filtered_train_X <- train_weight_X[valid_indices, ]
      filtered_train_E <- expanded_train_data_with_weight$E[valid_indices]
      filtered_weights <- expanded_train_data_with_weight$IPCW[valid_indices]
      if(method == "cox"){
        penalty_model <- tryCatch({
                glmnet(
                  filtered_train_X, 
                  filtered_train_E, 
                  family = "cox", 
                  weights = filtered_weights, 
                  alpha = alpha_num, 
                  lambda = lambda_values
                )
              }, warning = function(w) {
                message("Warning in fitting glmnet for lambda = ", lambda, ": ",k , w$message)
                return(NULL)
              }, error = function(e) {
                message("Error in fitting glmnet for lambda = ", lambda, ": ", e$message)
                return(NULL)
              })
        formula = as.formula(paste("Surv(observed_time, sigma) ~", paste(var_name, collapse = " + ")))
        cox_model = coxph(formula, data = expanded_train_data_with_weight, method="breslow")
        baseline_hazard = basehaz(cox_model, centered=FALSE)
        BLH_timepoint = baseline_hazard$hazard[which.min(abs(baseline_hazard$time - time_point))]
      }
      else{
        penalty_model <- tryCatch({
          glmnet(
            filtered_train_X, 
            filtered_train_E, 
            family = "binomial", 
            weights = filtered_weights, 
            alpha = alpha_num, 
            lambda = lambda_values
          )
        }, warning = function(w) {
          message("Warning in fitting glmnet for lambda = ", lambda, ": ",k , w$message)
          return(NULL)
        }, error = function(e) {
          message("Error in fitting glmnet for lambda = ", lambda, ": ", e$message)
          return(NULL)
        })
      }
      
      for (i in seq_along(lambda_values)){
        coef = as.vector(coef(penalty_model, s=lambda_values[i]))
        if(all(coef==0)){
          est_test_event_probability = 1
        }
        else{
          intercept = coef[1]
          est_beta_lambda_i = coef[-1]
          test_lp = intercept + as.matrix(test_data[var_name]) %*% est_beta_lambda_i
          if(method=="cox"){
            # Cox regression
            est_test_surv_probability = exp(-BLH_timepoint*exp(test_lp))
            est_test_event_probability = 1 - est_test_surv_probability
          }
          else{
            # logistic regression
            est_test_event_probability = exp(test_lp) / (1 + exp(test_lp))
            est_test_surv_probability = 1-est_test_event_probability
          }
          fold_performance_metric[i, 1, f] = ols_error(test_true_surv, est_test_surv_probability)
          fold_performance_metric[i,2,f] = c_index_censoring(test_data$observed_time,
                                                       test_data$sigma,
                                                       est_test_event_probability)
          fold_performance_metric[i,3,f] = weighted_loglikelihood(test_IPCW, 
                                                        test_data$E, 
                                                        est_test_event_probability)
        }
      }
    }
    for (i in seq_along(lambda_values)) {
      results[i, num_intervals, 1] = mean(fold_performance_metric[i, 1, ], na.rm = TRUE)
      results[i, num_intervals, 2] = mean(fold_performance_metric[i, 2, ], na.rm = TRUE)
      results[i, num_intervals, 3] = mean(fold_performance_metric[i, 3, ], na.rm = TRUE)
    }
  }
  return(results)
}
```

