---
title: "Multilayer_IPCW"
author: "Liyan Wang"
date: "2024-09-21"
output: html_document
---
```{r}
rm(list = ls())
library(survival)
library(dplyr)
library(caret)
library(ggplot2)
library(knitr)
knitr::purl("~/IPCweighting/IPCWmethod.Rmd", output = "~/IPCweighting/IPCWmethod.R")
source("~/IPCweighting/IPCWmethod.R")
knitr::purl("~/IPCweighting/estimation_naive_cox_ipcw.Rmd", output = "~/IPCweighting/estimation_naive_cox_ipcw.R")
source("~/IPCweighting/estimation_naive_cox_ipcw.R")
```

```{r}
num_obs = 1000
dist = "exponential"
params = list()
time_point = 5
if(dist=="exponential"){
  params$lambda_base = 0.5
  lambda_base = params$lambda_base
}else if(dist == "Weibull"){
  params$lambda_base = 2
  params$alpha = 0.5
} else if(dist == "log-logistic"){
  params$lambda_base = 4
  params$alpha = 1.2
} else if (dist == "log-normal"){
  params$mean = 2
  params$sd = 0.7
} else{
  stop("Unsupported distribution")
}
```

```{r}
# Simulate covariates and event_time
X = matrix(ncol = 0, nrow = 0)
mean_X = c()
X = get_cont_X(X, 'uniform',num_obs,1,4,"X1")
X = get_cont_X(X, 'uniform',num_obs,0.2,1,"X2")
beta = sim_beta(0.6, time_point, mean_X) #sim_beta("uniform", length(mean_X),list(start = -2, end = 2))
if (ncol(X)!=length(beta)){
  stop("X and beta are not multiplicable")
}
params$lc = rowSums(sweep(X,2,beta,"*"))
power = exp(rowSums(sweep(X,2,beta,"*")))
dt = data.frame(power = power)
dt = cbind(dt,X)
var_name = colnames(X)
dt$event_time = sim_T(dist, num_obs, params=params, TRUE)
```

```{r}
# simulate censoring time
censor_params = list()
censor_dist = "uniform"
if(censor_dist=="exponential"){
  censor_params$lambda = 0.5
}else if(censor_dist == "Weibull"){
  censor_params$lambda = 2
  censor_params$alpha = 0.5
} else if(censor_dist == "log-logistic"){
  censor_params$lambda = 4
  censor_params$alpha = 1.2
} else if (censor_dist == "log-normal"){
  censor_params$mean = 2
  censor_params$sd = 0.7
} else if (censor_dist == "uniform"){
  censor_params$start = 1
  censor_params$end = 7
} else{
  stop("Unsupported distribution")
}
dt$censor_time = sim_censor_time(censor_dist, num_obs, params = list(start = 2.5, end = 9))
```

```{r}
dt$observed_time = pmin(dt$event_time, dt$censor_time)
dt$sigma = as.numeric(dt$event_time<dt$censor_time)
dt$E = get_status(dt$observed_time, dt$sigma, time_point)
print(check_time_vs_status(dt))
print(check_censor_in_time_interval(dt,time_point))
```

```{r}
Ghat = Get_Ghat(time_point, dt)
multilayer_ipcw<-function(interval,train_data){
  # This is used to get the model of "binned" IPCW
  total=data.frame()
  for(i in 1:(length(interval)-1)){
    start = interval[i]
    end = interval[i+1]
    numerator = Ghat(start)
    batch = train_data[train_data$observed_time>start,]
    batch$E = NULL
    batch$E = get_status(batch$observed_time,batch$sigma,end)
    batch$G = ifelse(batch$observed_time<end, Ghat(batch$observed_time),Ghat(end))
    batch$IPCW = ifelse(pmin(batch$event_time, end)<batch$censor_time, 
                                  numerator/batch$G, 
                                  0)
    if (ncol(total) == 0) {
      total = data.frame(batch)
    } else {
      total = rbind(total, batch)
    }
  }
  formula_str = paste("E ~", paste(var_name, collapse = " + "))
  formula = as.formula(formula_str)
  model = glm(formula, data = total, family = binomial, weights = IPCW)
  return(model)
}
```

```{r, warning=FALSE}
# Cross Validation, binning intervals equally
max_intervals = 60
k = 5
Ghat = Get_Ghat(time_point, dt)
folds = createFolds(dt$event_time, k = k)
results = data.frame(intervals = 1:max_intervals, performance = NA)
for (num_intervals in 1:max_intervals) {
  fold_performance = numeric(k)
  for (f in 1:k) {
    train_data = dt[-folds[[f]], ]
    test_data = dt[folds[[f]], ]
    interval = seq(0, time_point, length.out = num_intervals + 1)
    model = multilayer_ipcw(interval, train_data)
    test_data$pred_prob = 1 - predict(model, newdata = test_data[var_name], type = "response")
    test_true_surv = (true_survival_function(dist, time_point, params = params))^exp(rowSums(sweep(test_data[var_name],2,beta,"*")))
    fold_performance[f] = ols_error(test_true_surv, (test_data$pred_prob)^num_intervals)
}
  results$performance[num_intervals] = mean(fold_performance)
  
}
best_intervals = results$intervals[which.min(results$performance)]
print(paste("Optimal number of intervals:", best_intervals))
```

```{r}
# Plot of performance with respect to the number of bins
plot(x=c(1:max_intervals), y = results$performance, xlab = "Number of Intervals", ylab = "OLS_Error")
```

```{r}
# Compute 1 bin IPCW ols_error
true_surv = (true_survival_function(dist, time_point, params = params))^power
ipcw_est_surv = ipcw_estimate(dt,dt, time_point, var_name)
ols_ipcw = ols_error(true_surv,ipcw_est_surv)

# Compute optimal_bin IPCW ols_error
opt_interval = seq(0, time_point, length.out = best_intervals + 1)
multi_ipcw_model = multilayer_ipcw(opt_interval, dt)
multi_layer_ipcw_pred_prob = 1-(predict(multi_ipcw_model, newdata = dt[var_name], type = "response"))
ols_multi_ipcw = ols_error(true_surv, (multi_layer_ipcw_pred_prob)^best_intervals)
ols_multi_ipcw
```
